engines:
  pmd:
    fileExclusions:
      - force-app/main/default/classes/Excluded/**
      - force-app/main/default/classes/DMLAuditAI.cls

  cpd:
    fileExclusions:
      - force-app/main/default/classes/Excluded/**
      - force-app/main/default/classes/DMLAuditAI.cls
    minimum_tokens:
      apex: 50
  eslint:
    auto_discover_eslint_config: true 
    disable_lwc_base_config: true
    file_extensions:
      - js
      - mjs
      - jsx

  eslint:
    enabled: true
  pmd:
    enabled: true
  cpd:
    enabled: true
  flow-scanner:
    enabled: true
  regex:
    enabled: true
  retirejs:
    enabled: true
