engines:
  eslint:
    eslint_ignore_file: .eslintignore

  retirejs:
    exclude_patterns:
      - force-app/main/default/lwc/Excluded/**
      - force-app/main/default/lwc/dmlAverage/**

  pmd:
    fileExclusions:
      - force-app/main/default/classes/Excluded

  cpd:
    fileExclusions:
      - force-app/main/default/classes/Excluded
    minimum_tokens:
      apex: 50

  regex:
    fileExclusions:
      - "force-app/main/default/lwc/Excluded/**"
      - "force-app/main/default/lwc/dmlAverage/**"

  flow:
    fileExclusions:
      - force-app/main/default/flows/Excluded
      - force-app/main/default/flows/Send_Email_on_New_Account_Creation.flow-meta.xml
