engines:
  pmd:
    fileExclusions:
      - force-app/main/default/classes/Excluded/**
      - force-app/main/default/classes/DMLAuditAI.cls

  cpd:
    fileExclusions:
      - force-app/main/default/classes/Excluded/**
      - force-app/main/default/classes/DMLAuditAI.cls
    minimum_tokens:
      apex: 50
