name: Salesforce Code Analyzer Workflow

on:
  pull_request:
    paths:
      - 'force-app/main/default/classes/**'
      - 'config/pmd/**'

jobs:
  salesforce-code-analyzer-workflow:
    permissions:
      pull-requests: write
      contents: read
      actions: read
    runs-on: ubuntu-latest

    steps:
      - name: Check out files
        uses: actions/checkout@v5

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Latest Salesforce Code Analyzer CLI Plugin
        run: sf plugins install code-analyzer@latest


      - name: Get changed Apex files
        id: changed
        run: |
          echo "CHANGED_FILES=$(git diff origin/${{ github.base_ref }}...HEAD --name-only | grep 'force-app/main/default/classes/' | grep -v 'ExcludedFile.cls' | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Run Salesforce Code Analyzer on changed files
        run: |
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed Apex files to analyze"
          else
            echo "Analyzing changed files: $CHANGED_FILES"
            sf code-analyzer run $CHANGED_FILES --config-file sfca-config.yml --view detail --output-file sfca_results.html --output-file sfca_results.json
          fi
      - name: Upload SFCA results
        uses: actions/upload-artifact@v4
        with:
          name: sfca-results
          path: |
            sfca_results.html
            sfca_results.json
        
      - name: Fail on Critical/High Violations (Changed Files Only)
        if: |
          steps.run-code-analyzer.outputs.num-sev1-violations-in-changed-files > 0 ||
          steps.run-code-analyzer.outputs.num-sev2-violations-in-changed-files > 0
        run: exit 1
