name: old  Salesforce Code Analyzer Workflow

on:
  pull_request:
    paths:
      - 'force-app/main/default/**'
      - 'sfca-config.yml'


jobs:
  sfca:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 

      # -------------------------------
      # Setup Node and Salesforce CLI
      # -------------------------------


      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest
      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install code-analyzer@latest


      # -------------------------------
      # Install yq (YAML parser)
      # -------------------------------
      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Get changed Apex files
        id: changed
        run: |
          CHANGED_FILES=$(git diff origin/${{ github.base_ref }}...HEAD \
            --name-only \
            --diff-filter=ACM \
            | grep '^force-app/main/default/classes/.*\.cls$' \
            | tr '\n' ' ')
      
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
          echo "Changed files: $CHANGED_FILES"
        
      
      # -------------------------------
      # Run Salesforce Code Analyzer(without --rule-selector sfge )
      # -------------------------------
      - name: Run Salesforce Code Analyzer (changed files only)
        if: ${{ env.CHANGED_FILES != '' }}
        uses: forcedotcom/run-code-analyzer@v2  
        with:
          run-arguments: --workspace  --config-file sfca-config.yml --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results
          github-token: ${{ github.token }}

      # - name: Run Graph Engine safely
      #   if: ${{ env.CHANGED_FILES != '' }}
      #   run: |
      #     echo "Running Graph Engine..."
      #     sf code-analyzer run --target ${{ env.CHANGED_FILES }} --rule-selector sfge --view detail --output-file sfge_results.html || true
      #     echo "SFGE finished (errors may exist in sfge_results.html)"
          
      
      #   # -------------------------------
      #   # Upload SFGE Report as Artifact
      #   # -------------------------------
      # - name: Upload SFGE results
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: sfge-results
      #     path: sfge_results.html