name: standard Salesforce Code Analyzer Workflow

on:
  pull_request:
    paths:
      - "force-app/main/default/**"
      - "code.yml"

jobs:
  sfca:
    runs-on: ubuntu-latest

    steps:
      # -------------------------------
      # Checkout repository
      # -------------------------------
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # -------------------------------
          # Install Node dependencies
          # -------------------------------
      - name: Install Node dependencies
        run: |
          npm install --save-dev eslint@latest @salesforce/eslint-config-lwc @salesforce/eslint-plugin-aura eslint-plugin-jest

      - name: Install dependencies
        run: npm install
      # - name: Install Jest
      #   run: npm install --save-dev jest
      # 3️⃣ Download and setup PMD
      - name: Download and Setup PMD
        run: |
          wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F6.55.0/pmd-bin-6.55.0.zip
          unzip pmd-bin-6.55.0.zip
          chmod +x pmd-bin-6.55.0/bin/run.sh
      # -------------------------------
      # Install Salesforce CLI and Code Analyzer plugin
      # -------------------------------
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Install Salesforce Code Analyzer Plugin
        run: sf plugins install code-analyzer@latest

      # -------------------------------
      # Install yq (YAML parser)
      # -------------------------------
      # - name: Install yq
      #   run: |
      #     sudo wget -qO /usr/local/bin/yq \
      #       https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
      #     sudo chmod +x /usr/local/bin/yq
      #     # -------------------------------
      # Read all exclusions from sfca-config.yml
      # -------------------------------
      # - name: Read all exclusions from sfca-config.yml
      #   run: |
      #     engines=("pmd" "cpd" "eslint" "regex" "retirejs" "flow" "graph")
      #     for engine in "${engines[@]}"; do
      #       EXCLUSIONS=$(yq ".engines.${engine}.fileExclusions[]" sfca-config.yml || true)
      #       EXCLUSIONS=$(echo "$EXCLUSIONS" | tr '\n' ' ' | sed 's/ $//')
      #       echo "${engine^^}_EXCLUSIONS=$EXCLUSIONS" >> $GITHUB_ENV
      #     done

      # -------------------------------
      # Get changed files from PR
      # -------------------------------
      # - name: Get all changed files
      #   id: changed
      #   run: |
      #     # Fetch base branch
      #     git fetch origin ${{ github.base_ref }}

      #     # Get all changed files under force-app/main/default/
      #     CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD \
      #       | grep '^force-app/main/default/' || true)>> $GITHUB_ENV

      - name: Run PMD CPD
        run: |
          ./pmd-bin-6.55.0/bin/run.sh cpd \
          --minimum-tokens 20 \
          --language apex \
          --dir force-app/main/default/classes \
          --exclude force-app/main/default/classes/UserPermissionsLoggerBatch.cls \
          --format text > cpd-report.txt
      # - name: Run Salesforce Code Analyzer
      #   id: run-code-analyzer
      #   uses: forcedotcom/run-code-analyzer@v2
      #   with:
      #     run-arguments: --workspace .${{ env.CHANGED_FILES }} --config-file code.yml --view detail --output-file sfca_results.html --output-file sfca_results.json
      #     results-artifact-name: salesforce-code-analyzer-results
      #     github-token: ${{ github.token }}
