name: standard Salesforce Code Analyzer Workflow

on:
  pull_request:
    paths:
      - "force-app/main/default/**"
      - "sfac.yml"

jobs:
  sfca:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          # -------------------------------
          # Install Node dependencies
          # -------------------------------
      - name: Install Node dependencies
        run: |
          npm install --save-dev eslint@latest @salesforce/eslint-config-lwc @salesforce/eslint-plugin-aura eslint-plugin-jest

      # -------------------------------
      # Get changed files from PR
      # -------------------------------
      - name: Get all changed files
        id: changed
        run: |
          # Fetch base branch
          git fetch origin ${{ github.base_ref }}

          # Get all changed files under force-app/main/default/
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD \
            | grep '^force-app/main/default/' || true)>> $GITHUB_ENV

      # -------------------------------
      # Install Salesforce CLI and Code Analyzer plugin
      # -------------------------------
      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli@latest

      - name: Run Salesforce Code Analyzer
        id: run-code-analyzer
        uses: forcedotcom/run-code-analyzer@v2
        with:
          run-arguments: --workspace .${{ env.CHANGED_FILES }} --config-file sfac.yml --view detail --output-file sfca_results.html --output-file sfca_results.json
          results-artifact-name: salesforce-code-analyzer-results
